cache:
  paths:
    - client/node_modules/
    - client/dist/



stages:
  - init
  - lint
  - build
  - test
  - staging
  - production

init_modules:
  stage: init
  script:
    - cd client
    - npm ci
  tags:
    - nodejs

lint_testing:
  stage: lint
  script:
    - cd client
    - npm run lint
    - cd ../server
    - npm run lint
  tags:
    - nodejs

build:
  stage: build
  script:
    - cd client
    - npm run build
  tags:
    - nodejs

karma_testing:
  stage: test
  script:
    - cd client
    - npm run karma
  tags:
    - nodejs

api_testing:
  stage: test
  script:
    - cd server
    - npm run test
  tags:
    - nodejs



staging:
  stage: staging
  image: ruby:latest
  script:
    - echo "Deploy to staging server"
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  environment:
    name: staging
    url: http://www.staging.jindr.de
  only:
    - staging
  tags:
    - ruby2



production:
  stage: production
  image: ruby:latest
  script:
    - echo "Deploy to production server"
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  environment:
    name: staging
    url: http://www.jindr.de
  only:
    - master
  tags:
    - ruby2
