POST http://localhost:8080/register
Content-Type: application/json

{
  "user": {
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@doe.de",
    "password": "johndoe"
  }
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@test.de",
  "password": "test123",
  "deviceID": "abc1234rst12"
}

###
GET http://localhost:8080/login/abc1234rst12
Accept: application/json

###

POST http://localhost:8080/logout
Content-Type: application/json

{
  "userID": "5ecf8d4fb6f1da394c25d7e0"
}

###

PUT http://localhost:8080/update-user
Content-Type: application/json

{
  "user": {
    "_id": "5ed27c926c31d33518cc81c2",
    "firstName": "Hallo",
    "lastName": "Test",
    "email": "valle@test.de"
  },
  "password": "test123"
}

###
GET http://localhost:8080/user/5ed27c926c31d33518cc81c2
Accept: application/json

###
