POST http://localhost:8080/register
Content-Type: application/json

{
  "user": {
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@doe.de",
    "password": "johndoe"
  }
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@test.de",
  "password": "test123",
  "deviceID": "abc1234rst12"
}

###
GET http://localhost:8080/login/abc1234rst12
Accept: application/json

###

POST http://localhost:8080/logout
Content-Type: application/json

{
  "userID": "5ecf8d4fb6f1da394c25d7e0"
}

###

PUT http://localhost:8080/update-user
Content-Type: application/json

{
  "user": {
    "_id": "5ed27c926c31d33518cc81c2",
    "firstName": "Hallo",
    "lastName": "Test",
    "email": "valle@test.de"
  },
  "password": "test123"
}

###
GET http://localhost:8080/user/5ed27c926c31d33518cc81c2
Accept: application/json

###
PUT http://localhost:8080/job-stack
Content-Type: application/json

{
  "user": {
    "_id": "5ee24164c71c594a94003ea3",
    "distance": 10
  },
  "coords": {
    "lat": 51.3260435992175,
    "lng": 9.72345094553722
  }
}

###
POST http://localhost:8080/create-job
Content-Type: application/json

{
  "coords": {
    "lat": 50.5820767,
    "lng": 8.6662563
  },
  "job": {
    "title": "Ein Test Job8",
    "description": "Bla Bla",
    "creator": "5ee24164c71c594a94003ea3",
    "location": {
      "lat": 50.5820767,
      "lng": 8.6662563
    }
  }
}
